"""Keep DTK section placement independent of its generated unit order."""

import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import analyze
import source_build


class SDKAnalysisPlacement(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.directory = Path(self.temporary.name).resolve()
        self.target = {"entry": "0x80003100", "sda_base": "0x803F22A0",
                       "sda2_base": "0x804022A0"}
        self.sections = [{"name": ".text", "output": ".text", "start": 0x1000,
                          "end": 0x100C},
                         {"name": ".data5", "output": ".sdata", "start": 0x2000,
                          "end": 0x2008}]
        self.sdk = [{"name": "src/dolphin/gx/GX.c", "sections": [
            {"section": ".text", "start": "0x00001004", "end": "0x00001008"},
            {"section": ".data5", "start": "0x00002000", "end": "0x00002004"},
        ]}]
        self.objects = [
            self.object("auto_01_00001008_text", "late.o", [(".text", 4)]),
            self.object("src/dolphin/gx/GX.c", "GX.o", [(".text", 4), (".data5", 4)], False),
            self.object("auto_01_00001000_text", "early.o", [(".text", 4)]),
            self.object("auto_06_00002004_data5", "data.o", [(".data5", 4)]),
        ]

    def object(self, name, filename, sections, automatic=True):
        path = self.directory / filename
        source_build.write_object(path, [{"name": section, "type": 1, "flags": 2,
                                      "size": size, "data": b"\0" * size}
                                     for section, size in sections], [])
        return {"name": name, "object": str(path), "autogenerated": automatic}

    def script(self):
        return analyze.split_link_script(self.target, self.sections, self.objects,
                                         self.sdk, {"_stack_end": "0x803ED681"})

    def test_per_section_target_order_overrides_generated_unit_order(self):
        script = self.script()
        self.assertIn(f'.text 0x00001000 : {{ "{self.directory}/early.o"(.text) "{self.directory}/GX.o"(.text) "{self.directory}/late.o"(.text) }}', script)
        self.assertIn(f'.sdata 0x00002000 : {{ "{self.directory}/GX.o"(.data5) "{self.directory}/data.o"(.data5) }}', script)
        self.assertIn("_stack_end = 0x803ED681;", script)
        self.objects.reverse()
        self.assertEqual(script, self.script())

    def test_missing_chunk_is_rejected(self):
        self.objects.pop(2)
        with self.assertRaisesRegex(ValueError, "partition"):
            self.script()

    def test_overlapping_chunk_is_rejected(self):
        self.objects[0]["name"] = "auto_01_00001004_text"
        with self.assertRaisesRegex(ValueError, "partition"):
            self.script()

    def test_expanded_sdk_object_cannot_change_recorded_extent(self):
        self.objects[1] = self.object("src/dolphin/gx/GX.c", "GX.o",
                                      [(".text", 8), (".data5", 4)], False)
        with self.assertRaisesRegex(ValueError, "size differs"):
            self.script()

    def test_unrecorded_source_unit_is_rejected(self):
        self.objects[1]["name"] = "src/dolphin/gx/Other.c"
        with self.assertRaisesRegex(ValueError, "no recorded"):
            self.script()

    def test_unrecorded_extra_section_is_rejected(self):
        self.objects[1] = self.object("src/dolphin/gx/GX.c", "GX.o",
                                      [(".text", 4), (".data5", 4), (".data4", 4)], False)
        with self.assertRaisesRegex(ValueError, "sections differ"):
            self.script()

    def test_separated_same_section_extents_cannot_be_concatenated(self):
        self.sdk[0]["sections"].append({"section": ".text", "start": "0x00001008",
                                        "end": "0x0000100C"})
        with self.assertRaisesRegex(ValueError, "separated extents"):
            self.script()

    def test_autogenerated_name_must_encode_target_location(self):
        self.objects[0]["name"] = "auto_unknown"
        with self.assertRaisesRegex(ValueError, "cannot be identified"):
            self.script()

    def test_case_insensitive_suffixes_use_distinct_exact_inputs(self):
        self.objects[0] = self.object("auto_01_00001008_text", "CARDBios.o", [(".text", 4)])
        self.objects[1] = self.object("src/dolphin/gx/GX.c", "OS.o",
                                      [(".text", 4), (".data5", 4)], False)
        script = self.script()
        self.assertIn(f'"{self.directory}/OS.o"(.text)', script)
        self.assertIn(f'"{self.directory}/CARDBios.o"(.text)', script)
        self.assertNotIn("*", script)

    def test_exact_selector_cannot_contain_script_syntax(self):
        self.objects[0]["object"] = str(self.directory / 'evil".o')
        with self.assertRaisesRegex(ValueError, "Unsafe exact"):
            self.script()

    def test_omitted_sdk_unit_is_rejected_even_if_auto_object_covers_it(self):
        self.objects[1] = self.object("auto_01_00001004_text", "GX.o", [(".text", 4)])
        with self.assertRaisesRegex(ValueError, "omitted"):
            self.script()

    def test_duplicate_object_basenames_are_rejected(self):
        nested = self.directory / "nested"
        nested.mkdir()
        (nested / "early.o").write_bytes(Path(self.objects[0]["object"]).read_bytes())
        self.objects[0]["object"] = str(nested / "early.o")
        with self.assertRaisesRegex(ValueError, "distinct object"):
            self.script()


class SDKAssemblyExport(unittest.TestCase):
    def exercise(self, output, failure=False):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            name = "src/dolphin/gx/GX.c"
            assembly = directory / "asm/src/dolphin/gx/GX.s"
            assembly.parent.mkdir(parents=True)
            assembly.write_bytes(b"stale assembly")
            commands = []

            def stage(command, log):
                commands.append(command)
                self.assertFalse(assembly.exists())
                if failure:
                    raise RuntimeError("Unsupported SDK relocation")
                if output is not None:
                    Path(command[-1]).write_bytes(output)

            objects = [{"name": "auto_01_00001000_text", "object": "unrelated.o"},
                       {"name": name, "object": "SDK.o"}]
            with patch.object(analyze, "run", side_effect=stage):
                analyze.sdk_assembly(directory / "dtk", directory, objects, [{"name": name}])
            self.assertEqual(len(commands), 1)
            self.assertEqual(commands[0][1:4], ["elf", "disasm", "SDK.o"])
            self.assertEqual(assembly.read_bytes(), output)

    def test_only_sdk_objects_get_private_assembly(self):
        self.exercise(b"fresh SDK assembly")

    def test_stale_assembly_cannot_satisfy_zero_exit(self):
        with self.assertRaisesRegex(RuntimeError, "no fresh assembly"):
            self.exercise(None)

    def test_empty_assembly_is_rejected(self):
        with self.assertRaisesRegex(RuntimeError, "no fresh assembly"):
            self.exercise(b"")

    def test_unsupported_sdk_assembly_is_fatal(self):
        with self.assertRaisesRegex(RuntimeError, "Unsupported SDK relocation"):
            self.exercise(None, failure=True)


class ReviewedSDKDataSeeds(unittest.TestCase):
    def setUp(self):
        self.unit = {"source": "src/dolphin/pad/Padclamp.c", "sections": [
            {"section": ".data3", "start": "0x802B7258", "end": "0x802B7262"}]}
        self.accepted = [{"source": self.unit["source"], "sections": [
            {"placement": ".data3", "start": "0x802B7258", "end": "0x802B7262"}]}]

    def test_reviewed_native_size_does_not_absorb_alignment_padding(self):
        seed = analyze.sdk_data_seeds([self.unit], self.accepted)
        self.assertEqual(seed, "sdk_data_802B7258 = .data3:0x802B7258; // type:object size:0xA\n")

    def test_unreviewed_data_extent_is_not_seeded(self):
        self.assertEqual(analyze.sdk_data_seeds([self.unit], []), "")

    def test_unreviewed_extent_change_is_not_seeded(self):
        self.unit["sections"][0]["end"] = "0x802B7264"
        self.assertEqual(analyze.sdk_data_seeds([self.unit], self.accepted), "")

    def test_native_data_cannot_seed_a_code_boundary(self):
        self.unit["sections"][0]["section"] = ".text"
        self.accepted[0]["sections"][0]["placement"] = ".text"
        self.unit["sections"][0]["object_seed"] = True
        self.assertEqual(analyze.sdk_data_seeds([self.unit], self.accepted), "")


class OriginalDTKGeometry(unittest.TestCase):
    def geometry(self, loaded_size=4, bss_size=4):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            objects = []
            for name, section, address, size in [("text", ".text", 0x1000, loaded_size),
                                                 ("bss", ".bss", 0x2000, bss_size)]:
                path = directory / (name + ".o")
                source_build.write_object(path, [{"name": section, "type": 1, "flags": 2,
                                                  "size": size, "data": b"\0" * size}])
                objects.append({"name": f"auto_01_{address:08X}_{name}", "object": str(path),
                                "autogenerated": True})
            return analyze.original_geometry([
                {"name": ".text", "start": 0x1000, "end": 0x1004, "kind": "code"},
                {"name": ".bss", "start": 0x2000, "end": 0x2018, "kind": "bss"}], objects)

    def test_original_unallocated_bss_alignment_gap_stays_unassigned(self):
        sections = self.geometry()
        self.assertEqual(sections[1]["end"], 0x2004)
        self.assertEqual(sections[0]["end"], 0x1004)

    def test_loaded_bytes_cannot_be_treated_as_an_alignment_gap(self):
        with self.assertRaisesRegex(ValueError, "loaded target geometry"):
            self.geometry(loaded_size=2)

    def test_uninitialized_section_cannot_extend_beyond_target(self):
        with self.assertRaisesRegex(ValueError, "loaded target geometry"):
            self.geometry(bss_size=28)


class SDKByteFragmentAlignment(unittest.TestCase):
    def test_byte_fragments_do_not_relax_code_instruction_alignment(self):
        sections = analyze.section_description({".text": "code", ".data3": "rodata",
                                                ".sbss": "bss"}, byte_fragments=True)
        self.assertIn(".text type:code align:4", sections)
        self.assertIn(".data3 type:rodata align:1", sections)
        self.assertIn(".sbss type:bss align:1", sections)

    def test_original_geometry_keeps_existing_alignment(self):
        sections = analyze.section_description({".text": "code", ".data3": "rodata"})
        self.assertIn(".data3 type:rodata align:4", sections)


class UnassignedByteFragments(unittest.TestCase):
    def test_unowned_byte_gap_is_retained_without_source_ownership(self):
        sections = [{"name": ".data3", "start": 0x2000, "end": 0x2010}]
        sdk = [{"name": "src/dolphin/pad/Padclamp.c", "sections": [
            {"section": ".data3", "start": "0x00002000", "end": "0x0000200A"}]}]
        gaps = analyze.unassigned_splits(sections, sdk)
        self.assertEqual(gaps, [{"name": "unassigned/data3_0000200A", "sections": [
            {"section": ".data3", "start": "0x0000200A", "end": "0x0000200C"}]},
            {"name": "unassigned/data3_0000200C", "sections": [
            {"section": ".data3", "start": "0x0000200C", "end": "0x00002010"}]}])
        self.assertNotIn("source", gaps[0])
        splits = analyze.byte_aligned_split_text(sdk + gaps)
        self.assertIn("end:0x0000200A align:1", splits)
        self.assertIn("start:0x0000200A end:0x0000200C align:1", splits)

    def test_separated_owned_extents_leave_intervening_gap_unassigned(self):
        sdk = [{"name": "unit", "sections": [
            {"section": ".text", "start": "0x00001000", "end": "0x00001004"},
            {"section": ".text", "start": "0x00001008", "end": "0x00001010"}]}]
        gaps = analyze.unassigned_splits([{"name": ".text", "start": 0x1000, "end": 0x1010}], sdk)
        self.assertEqual(gaps[0]["sections"][0],
                         {"section": ".text", "start": "0x00001004", "end": "0x00001008"})
        self.assertNotIn("align:1", analyze.byte_aligned_split_text(gaps))


if __name__ == "__main__":
    unittest.main()
