#!/usr/bin/env python3
"""Generate provisional function metadata and verify the complete analyzed relink."""

import argparse
import hashlib
import json
import platform
import re
import shutil
import subprocess
from collections import Counter
from pathlib import Path

import baseline
import setup_compiler
import sdk_map
import source_build


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build" / "analysis"


def run(command, log):
    with log.open("w") as output:
        result = subprocess.run(command, cwd=ROOT, stdout=output,
                                stderr=subprocess.STDOUT, timeout=600)
    if result.returncode:
        raise RuntimeError(f"Command failed ({result.returncode}); see {log}")


def split_link_script(target, sections, objects, sdk_units, absolute_symbols):
    """Place each unchanged DTK object section at its recorded target extent."""
    named = {unit["name"]: unit for unit in sdk_units}
    pieces = {section["name"]: [] for section in sections}
    paths = [Path(unit["object"]) for unit in objects]
    if any(any(character in str(path) for character in ('"', "\n", "\r", "*", "?", "[", "]")) for path in paths):
        raise ValueError("Unsafe exact linker input path")
    if len({path.name for path in paths}) != len(paths):
        raise ValueError("DTK linker inputs require distinct object basenames")
    present = {unit["name"] for unit in objects if not unit.get("autogenerated")}
    if present - set(named):
        raise ValueError("DTK unit has no recorded target extent")
    if set(named) - present:
        raise ValueError("DTK omitted a recorded SDK unit")
    for unit, path in zip(objects, paths):
        elf_sections, _ = source_build.read_elf(path.read_bytes())
        allocated = [section for section in elf_sections
                     if section["flags"] & 2 and section["size"]]
        if unit.get("autogenerated"):
            match = re.fullmatch(r"auto_\d+_([0-9A-Fa-f]{8})_([A-Za-z0-9_]+)", unit["name"])
            if match is None or len(allocated) != 1:
                raise ValueError("Autogenerated DTK extent cannot be identified")
            declared = [{"section": "." + match[2], "start": "0x" + match[1],
                         "end": f"0x{int(match[1], 16) + allocated[0]['size']:08X}"}]
        elif unit["name"] in named:
            declared = named[unit["name"]]["sections"]
        else:
            raise ValueError(f"DTK unit has no recorded target extent: {unit['name']}")
        if len({extent["section"] for extent in declared}) != len(declared):
            raise ValueError("A DTK unit cannot combine separated extents of one section")
        extents = {extent["section"]: extent for extent in declared}
        if {section["name"] for section in allocated} != set(extents):
            raise ValueError(f"DTK sections differ from recorded extents: {unit['name']}")
        for section in allocated:
            extent = extents[section["name"]]
            start, end = int(extent["start"], 16), int(extent["end"], 16)
            if section["size"] != end - start or section["name"] not in pieces:
                raise ValueError(f"DTK section size differs from target extent: {unit['name']}")
            pieces[section["name"]].append({"start": start, "end": end,
                                           "object": path, "input": section["name"]})
    for section in sections:
        ordered = sorted(pieces[section["name"]], key=lambda piece: piece["start"])
        cursor = section["start"]
        for piece in ordered:
            if piece["start"] != cursor or piece["end"] > section["end"]:
                raise ValueError(f"DTK sections do not partition {section['name']} exactly")
            cursor = piece["end"]
        if cursor != section["end"]:
            raise ValueError(f"DTK sections leave a gap in {section['name']}")
        pieces[section["name"]] = ordered
    lines = ["ENTRY(__start)", "SECTIONS {", f"__start = {target['entry']};",
             f"_SDA_BASE_ = {target['sda_base']};", f"_SDA2_BASE_ = {target['sda2_base']};"]
    for section in sections:
        inputs = " ".join(f'"{piece["object"].resolve()}"({piece["input"]})'
                          for piece in pieces[section["name"]])
        lines.append(f"{section['output']} 0x{section['start']:08X} : {{ {inputs} }}")
    script = "\n".join(lines + ["}"]) + "\n"
    return script.removesuffix("}\n") + "".join(
        f"{name} = {address};\n" for name, address in absolute_symbols.items()) + "}\n"


def sdk_assembly(dtk, split, objects, sdk_units):
    """Render SDK objects privately without exporting unrelated game assembly."""
    sdk_names = {unit["name"] for unit in sdk_units}
    for unit in objects:
        if unit["name"] in sdk_names:
            assembly = split / "asm" / Path(unit["name"]).with_suffix(".s")
            assembly.parent.mkdir(parents=True, exist_ok=True)
            assembly.unlink(missing_ok=True)
            run([str(dtk), "elf", "disasm", unit["object"], str(assembly)],
                BUILD / "assembly.log")
            if not assembly.is_file() or not assembly.stat().st_size:
                raise RuntimeError(f"SDK disassembly produced no fresh assembly: {unit['name']}")


def sdk_data_seeds(sdk_units, source_units):
    """Seed exact reviewed native data extents, retaining surrounding padding."""
    accepted = {(unit["source"], extent["placement"], extent["start"], extent["end"])
                for unit in source_units for extent in unit["sections"]
                if extent["placement"] not in (".text", ".init")}
    return "".join(
        f"sdk_data_{extent['start'][2:]} = {extent['section']}:{extent['start']}; "
        f"// type:object size:0x{int(extent['end'], 16) - int(extent['start'], 16):X}\n"
        for unit in sdk_units for extent in unit["sections"]
        if extent["section"] not in (".text", ".init") and (extent.get("object_seed") or
        (unit.get("source"), extent["section"], extent["start"], extent["end"]) in accepted))


def original_geometry(sections, objects):
    """Keep original DTK allocation ends distinct from DOL alignment gaps."""
    observed = {}
    for unit in objects:
        match = re.fullmatch(r"auto_\d+_([0-9A-Fa-f]{8})_([A-Za-z0-9_]+)", unit["name"])
        allocated, _ = source_build.read_elf(Path(unit["object"]).read_bytes())
        allocated = [section for section in allocated if section["flags"] & 2 and section["size"]]
        if not unit.get("autogenerated") or match is None or len(allocated) != 1:
            raise ValueError("Original DTK geometry is not a complete section partition")
        name, start = "." + match[2], int(match[1], 16)
        if name in observed or allocated[0]["name"] != name:
            raise ValueError("Original DTK section geometry is ambiguous")
        observed[name] = (start, start + allocated[0]["size"])
    if set(observed) != {section["name"] for section in sections}:
        raise ValueError("Original DTK geometry omits an executable section")
    result = []
    for section in sections:
        start, end = observed[section["name"]]
        if start != section["start"] or not start < end <= section["end"] \
                or (section["kind"] != "bss" and end != section["end"]):
            raise ValueError("Original DTK allocation differs from loaded target geometry")
        result.append({**section, "end": end})
    return result


def section_description(kinds, byte_fragments=False):
    return "Sections:\n" + "".join(
        f"\t{name} type:{kind} align:{1 if byte_fragments and kind != 'code' else 4}\n"
        for name, kind in kinds.items())


def unassigned_splits(sections, sdk_units):
    """Retain unowned gaps as neutral objects, including byte-aligned data."""
    units = []
    for section in sections:
        extents = sorted((int(extent["start"], 16), int(extent["end"], 16))
                         for unit in sdk_units for extent in unit["sections"]
                         if extent["section"] == section["name"])
        cursor = section["start"]
        for start, end in extents + [(section["end"], section["end"])]:
            if cursor < start:
                # SN relocates data words relative to each input's aligned origin.
                # A leading raw byte fragment has no inferred source ownership.
                boundary = (min(start, (cursor + 3) & ~3)
                            if section["name"] not in (".text", ".init") else cursor)
                cuts = [cursor] + ([boundary] if cursor < boundary < start else []) + [start]
                for first, last in zip(cuts, cuts[1:]):
                    units.append({"name": f"unassigned/{section['name'][1:]}_{first:08X}",
                                  "sections": [{"section": section["name"],
                                                "start": f"0x{first:08X}", "end": f"0x{last:08X}"}]})
            cursor = end
    return units


def byte_aligned_split_text(units):
    lines = sdk_map.split_text(units).splitlines()
    return "\n".join(line + (" align:1" if line.startswith("\t")
                           and line.split()[0] not in (".text", ".init") else "")
                      for line in lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--original", type=Path, required=True)
    args = parser.parse_args()
    (BUILD / "summary.json").unlink(missing_ok=True)
    original = args.original.resolve()
    target_dir = ROOT / "config" / "GN7E69"
    target = json.loads((target_dir / "baseline.json").read_text())
    plan = json.loads((target_dir / "analysis.json").read_text())
    data = original.read_bytes()
    if len(data) != target["size"] or hashlib.sha1(data).hexdigest() != target["sha1"]:
        raise RuntimeError("Original executable does not match the configured target")
    sections = source_build.target_sections(data, target, plan["output_sections"])
    logical_sdk_units = sdk_map.load(ROOT, sections)
    sdk_units = sdk_map.object_units(logical_sdk_units)
    system = f"{platform.system().lower()}-{platform.machine().lower()}"
    system = {"darwin-arm64": "macos-arm64", "linux-amd64": "linux-x86_64"}.get(system, system)
    lock = json.loads((ROOT / "tools" / "baseline-tools.json").read_text())
    if system not in lock["dtk"]:
        raise RuntimeError(f"Unsupported analysis host: {system}")
    dtk = baseline.get_tool("dtk", lock, system)
    compiler, wrapper = setup_compiler.setup()
    BUILD.mkdir(parents=True, exist_ok=True)
    split = BUILD / "split"
    if split.exists():
        shutil.rmtree(split)
    symbols = BUILD / "symbols.txt"
    splits = BUILD / "splits.txt"
    source_units = (json.loads((target_dir / "units.json").read_text())["units"]
                    if sdk_units else [])
    seed_text = "".join(
        f"{item['symbol']} = .text:{item['start']}; // type:{kind} "
        f"size:0x{int(item['end'], 16) - int(item['start'], 16):X}\n"
        for key, kind in (("data_ranges", "object"), ("function_seeds", "function"))
        for item in plan[key]
    )
    section_text = section_description(plan["section_kinds"])
    symbols.write_text(seed_text)
    splits.write_text(section_text)
    config = BUILD / "config.yml"
    config.write_text(
        f"object: {json.dumps(str(original))}\nhash: {target['sha1']}\n"
        f"symbols: {json.dumps(str(symbols))}\nsplits: {json.dumps(str(splits))}\n"
        "write_asm: false\nskip_cfa_ranges:\n"
        + "".join(f"  - start: .text:{r['start']}\n    end: .text:{r['end']}\n"
                  for r in plan["data_ranges"])
        + "block_relocations:\n"
        + "".join(f"  - source: .text:{r['start']}\n    end: .text:{r['end']}\n"
                  for r in plan["data_ranges"])
    )
    unassigned = []
    if sdk_units:
        geometry = BUILD / "geometry"
        if geometry.exists():
            shutil.rmtree(geometry)
        run([str(dtk), "dol", "split", "-j", "1", str(config), str(geometry)],
            BUILD / "geometry.log")
        geometry_units = json.loads((geometry / "config.json").read_text())["units"]
        sections = original_geometry(sections, geometry_units)
        logical_sdk_units = sdk_map.load(ROOT, sections)
        sdk_units = sdk_map.object_units(logical_sdk_units)
        unassigned = unassigned_splits(sections, sdk_units)
        symbols.write_text(seed_text + sdk_data_seeds(sdk_units, source_units))
        splits.write_text(section_description(plan["section_kinds"], byte_fragments=True)
                          + byte_aligned_split_text(sdk_units + unassigned))
    run([str(dtk), "dol", "split", "-j", "1", str(config), str(split)],
        BUILD / "analysis.log")
    split_config = json.loads((split / "config.json").read_text())
    if not sdk_units:
        sections = original_geometry(sections, split_config["units"])
    sdk_assembly(dtk, split, split_config["units"], sdk_units)
    rows = symbols.read_text().splitlines()
    functions = [r for r in rows if "type:function" in r]
    for region in plan["data_ranges"]:
        for row in functions:
            address = int(re.search(r"= [^:]+:(0x[0-9A-Fa-f]+)", row)[1], 16)
            if int(region["start"], 16) <= address < int(region["end"], 16):
                raise RuntimeError(f"Function inferred inside annotated data: {row}")
    units = split_config["units"]
    script = BUILD / "link.ld"
    script.write_text(split_link_script(target, sections, units, sdk_units + unassigned,
                                        plan["absolute_symbols"]))
    elf, output = BUILD / "main.elf", BUILD / "main.dol"
    for path in (elf, output):
        path.unlink(missing_ok=True)
    # Exact selectors load each input; listing them again would load objects twice.
    run([str(wrapper), str(compiler / "ngcld.exe"), "-T", str(script), "-o", str(elf)],
        BUILD / "link.log")
    run([str(dtk), "elf2dol", str(elf), str(output)], BUILD / "convert.log")
    result = output.read_bytes()
    if result != data or hashlib.sha1(result).hexdigest() != target["sha1"]:
        raise RuntimeError("Analyzed relink differs from the complete target")
    counts = Counter(re.search(r"type:(\w+)", r)[1] for r in rows if "type:" in r)
    (BUILD / "summary.json").write_text(json.dumps({
        "target_sha1": target["sha1"], "toolkit": lock["dtk"]["version"],
        "complete_relink": "identical", "inventory": "provisional",
        "candidate_counts": counts,
        "symbols_sha256": hashlib.sha256(symbols.read_bytes()).hexdigest(),
        "inputs": sdk_map.analysis_inputs(ROOT),
        "sdk_units": len(logical_sdk_units),
        "sdk_objects": len(sdk_units),
    }, indent=2) + "\n")
    print(f"Analyzed relink verified: {len(result)} bytes, SHA-1 {target['sha1']}")
    print("Generated names, function boundaries and source ownership remain provisional.")


if __name__ == "__main__":
    main()
