let sections=[];
const canvas=document.querySelector('#canvas');
function color(item){return item.matched===item.size?'var(--done)':item.matched>0?'var(--warm)':'var(--empty)'}
// Balanced area partitioning keeps byte proportions exact across viewport sizes.
function partition(items,x,y,w,h,out){if(!items.length)return;if(items.length===1){out.push({...items[0],x,y,w,h});return;}let total=items.reduce((s,a)=>s+a.size,0),sum=0,split=1;for(let i=0;i<items.length-1;i++){sum+=items[i].size;split=i+1;if(sum>=total/2)break;}const ratio=sum/total;if(w>=h){partition(items.slice(0,split),x,y,w*ratio,h,out);partition(items.slice(split),x+w*ratio,y,w*(1-ratio),h,out);}else{partition(items.slice(0,split),x,y,w,h*ratio,out);partition(items.slice(split),x,y+h*ratio,w,h*(1-ratio),out);}}
function render(){if(!sections.length)return;const layout=[];partition([...sections].sort((a,b)=>b.size-a.size),0,0,canvas.clientWidth,canvas.clientHeight,layout);canvas.replaceChildren();for(const item of layout){const block=document.createElement('div');block.className='tile';block.tabIndex=0;Object.assign(block.style,{left:item.x+'px',top:item.y+'px',width:item.w+'px',height:item.h+'px',background:color(item)});const description=`${item.name} · ${item.address} · ${item.size.toLocaleString()} bytes · source linked ${item.linked} B · source matched ${item.matched} B. Executable section; file/function mapping pending.`;block.setAttribute('aria-label',description);block.title=description;canvas.append(block);}}
function validMeasure(m){return m&&Number.isSafeInteger(m.total)&&m.total>0&&Number.isSafeInteger(m.linked)&&m.linked>=0&&m.linked<=m.total&&Number.isSafeInteger(m.matched)&&m.matched>=0&&m.matched<=m.linked;}
async function loadProgress(){try{const response=await fetch('./progress.json',{cache:'no-cache'});if(!response.ok)throw new Error('Progress unavailable');const data=await response.json();if(data.schema!==1||data.target!=='GN7E69'||data.basis!=='executable-sections'||data.baseline!=='verified'||!(/^[a-f0-9]{40}$/).test(data.revision)||!validMeasure(data.measures?.code)||!validMeasure(data.measures?.data)||!Array.isArray(data.sections)||!data.sections.length)throw new Error('Invalid progress');for(const item of data.sections){if(!['code','data'].includes(item.kind)||typeof item.name!=='string'||!/^0x[0-9A-F]{8}$/.test(item.address)||!validMeasure({total:item.size,linked:item.linked,matched:item.matched}))throw new Error('Invalid section');}for(const kind of ['code','data']){for(const field of ['total','linked','matched']){const sum=data.sections.filter(s=>s.kind===kind).reduce((n,s)=>n+s[field==='total'?'size':field],0);if(sum!==data.measures[kind][field])throw new Error('Inconsistent progress');}}
sections=data.sections;document.querySelectorAll('.progress-element').forEach((element,index)=>{const kind=index===0?'code':'data';const measures=data.measures[kind];element.title='Source-object bytes relative to executable section sizes; original objects do not count as source progress.';element.querySelectorAll('.track').forEach((track,row)=>{const field=row===0?'linked':'matched';const percent=measures[field]/measures.total*100;track.setAttribute('aria-valuenow',percent);track.removeAttribute('aria-valuetext');track.firstElementChild.style.width=percent+'%';track.previousElementSibling.lastElementChild.textContent=percent.toFixed(2)+'%';});});const link=document.querySelector('#build-link');link.href='https://github.com/mitsevox/nflstreet2/commit/'+data.revision;link.textContent='Baseline verified · '+data.revision.slice(0,7);link.title='Built '+data.built_at;render();}catch(error){document.querySelector('#build-link').textContent='Progress unavailable';canvas.textContent='Progress unavailable';document.querySelectorAll('.track').forEach(track=>track.setAttribute('aria-valuetext','Unavailable'));}}
new ResizeObserver(render).observe(canvas);loadProgress();
